# Generated by Django 4.2.22 on 2025-06-07 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_reporter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='product_img',
        ),
    ]
