# Generated by Django 4.2.22 on 2025-07-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_reporter', '0002_remove_manufacturer_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='low_stock_threshold',
            field=models.IntegerField(default=10),
        ),
    ]
