# Generated by Django 4.2.22 on 2025-07-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_reporter', '0003_manufacturer_low_stock_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='low_stock_threshold',
            field=models.IntegerField(default=5),
        ),
    ]
